pipeline:
  check_formatting:
    image: gradle:jdk17-alpine
    commands:
      - ./gradlew lintKotlin

  # - name: build the project
  #   user: root
  #   image: cimg/android:2022.12
  #   commands: 
  #     - ./gradlew assembleDebug
